; PlatformIO Project Configuration File
; ESP8266 NTP Clock with 16x2 I2C LCD
; https://github.com/ElectroIoT/ESP8266-NTC-Indian-Time-clock-Using-16x2-LCD

[env]
platform = espressif8266
framework = arduino
monitor_speed = 115200
lib_deps =
    marcoschwartz/LiquidCrystal_I2C@^1.1.4

[env:nodemcuv2]
board = nodemcuv2

[env:d1_mini]
board = d1_mini
